version: "3"

services:
  node_app_db:
    image: mysql:8
    container_name: node_app_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: node_app_core
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "6032:3306"
    volumes:
      - node_app_dbdata:/var/lib/mysql
    networks:
      - node_app_network

  node_app_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: node_app_phpmyadmin
    links:
      - node_app_db
    environment:
      PMA_HOST: node_app_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 8093:80
    networks:
      - node_app_network

  node_app_mongodb:
    image: mongo:4.4
    container_name: node_app_mongodb
    restart: unless-stopped
    ports:
      - 27018:27017
    networks:
      - node_app_network

volumes:
  node_app_dbdata:
    driver: local

networks:
  node_app_network:
    driver: bridge
